Add a  header toolbar and headline
benjaMatteo96/my-portfolio pull request #1
Opened 2023-05-31 21:19 UTC by benjaMatteo96

Hello, for this pull request:
- Add linter config.
- Add HTML and CSS with a toolbar and headline sections.
- Add a mediaquery.
- Update the readme file.
-

2023-05-31 22:03 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @benjaMatteo96, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 22:03 UTC, Qoosim commented on index.html
> +      </div>
- [ ] It is required that the list of social icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag). Kindly change this too.

2023-06-01 04:22 UTC, benjaMatteo96 commented
Updates:
- add changes to html and css files.
- add a hover to the nav logo.
- add a mit license to readme file.

2023-06-01 05:28 UTC, Cabraham1 requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @benjaMatteo96   :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following GitHubflow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:
- [ ] I kindly request that you adhere to the Figma design provided for your project. The Figma design serves as a visual reference and guideline for implementing the desired user interface and overall look of your application. Please ensure that the implemented code aligns with the design specifications provided in Figma. This includes aspects such as layout, color scheme, typography, and any other visual elements defined in the design.

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 05:28 UTC, Cabraham1 commented on README.md
> +This project is [MIT](./license) licensed.
- [ ] This project is [MIT](./license) licensed,' does not exist in the codebase, but you can include it, you can follow these steps to include the license file:

**[Here is MIcroverse Readme Template](https://github.com/microverseinc/readme-template)**

- Create a new file: Start by creating a new file in the root directory or in an appropriate location within the codebase. You can name it MIT.md, which is commonly used for license files.

- Choose the appropriate license: Determine the correct license for the project. In this case, it's the MIT license, as mentioned in the statement. The MIT license is an open-source license that allows users to freely use, modify, and distribute the software.

- Obtain the license text: Copy the text of the MIT license, from [Here is MIcroverse Readme Template](https://github.com/microverseinc/readme-template)

- Paste the license text: Open the newly created LICENSE file and paste the complete text of the MIT license into it. Make sure to edit any information specified in the license.

**By following these steps, you can include the MIT license file in the codebase, providing clarity about the licensing terms for the project.**

2023-06-01 05:28 UTC, Cabraham1 commented on index.html
> +    </div>
- [ ] [OPTIONAL] I kindly suggest that you centralize this section, because currently on my machine the section seems not to be centralized.
- [ ] Your design
![image](https://github.com/benjaMatteo96/my-portfolio/assets/68823331/34707b57-544d-4ce5-b811-d6f4dcad6793)


- [ ] Figma design
![image](https://github.com/benjaMatteo96/my-portfolio/assets/68823331/7cdfe490-0550-4863-bb92-df6a4489e886)

2023-06-01 15:13 UTC, benjaMatteo96 commented
@Cabraham1 @Qoosim Hello guys, I already have the MIT license, but I don't know why is not showing up on my README file, can you guys help me?
![MIT](https://github.com/benjaMatteo96/my-portfolio/assets/127891765/99518ed6-3bbe-4605-9d16-2c7b6eb569b6)

2023-06-01 15:44 UTC, benjaMatteo96 commented
@Cabraham1 Already update the following things:
- Create an MIT license.
- Update the README file with the MIT license in there.
- Update the CSS file.
- Update the "about" selector to centralize that element.

2023-06-01 16:06 UTC, christianbiring1 commented on styles/style.css
> +    background-image: url("/img/header-illsutration-mobile.svg");
- [ ] You may consider using the correct path for your background image.
```suggestion
    background-image: url("./img/header-illsutration-mobile.svg");
```

2023-06-01 16:32 UTC, benjaMatteo96 commented on index.html
> +    <div class="about">
@christianbiring1 Hello, on my computer I can see the background image, so I don't see the problem. What can I should do?

2023-06-01 16:37 UTC, benjaMatteo96 commented on index.html
> +    <div class="about">
@christianbiring1 Hello, on my computer I can see the background image, so I don't see the problem. What can I do?

2023-06-01 21:00 UTC, iambenkis approved these changes
## Hi @benjaMatteo96 ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
### Highlights
- Descriptive pull request  ✔️
- No linter errors ✔️
![approval](https://user-images.githubusercontent.com/65860678/198835698-769b7065-4290-4f20-a85c-cc03abb4d2ab.gif)

# Status: Approved ✔️✔️✔️

# Optional 

- [ ] [**OPTIONAL**] Kindly note that your commit messages are not written correctly , it should be capitalized as mention in the commit message convention. Kindly improve it in your projects 🛩️, For more information please check [this link](https://www.conventionalcommits.org/en/v1.0.0/)
![Capture](https://github.com/benjaMatteo96/my-portfolio/assets/80458199/ecc4b05c-6d71-4bf9-9382-04c9495800b6)
 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @iambenkis in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-02 12:46 UTC, merged