add-project-and-about-sections
benjaMatteo96/my-portfolio pull request #2
Opened 2023-06-08 15:53 UTC by benjaMatteo96

Hello, In this pull request: 
- Update HTML and CSS files with an about section and a project section.
- Update linters for the news elements.
- Add grid and flexbox for twice sections.

2023-06-08 16:34 UTC, divinecharlotte requested changes
Hi @benjaMatteo96       , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- Use of GitHub flow👍 
- Descriptive pr 👍 

 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [ ] Kindly consider adding a working link to your issue page under the contribution section to give a good user experience to the person who would like to interact with it 
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 16:34 UTC, divinecharlotte commented on index.html
> +        <button class="project-buttom">See Project</button>
- [ ] Kindly as requested by the previous reviewer consider adding button styling( Active, Hover, and Pressed) on your buttons to give a good user experience to the people visiting your website
 
<img width="634" alt="Screen Shot 2023-06-08 at 18 19 24" src="https://github.com/benjaMatteo96/my-portfolio/assets/60146030/d9f02bd3-98a7-43ae-94a8-d4c212a2ddd7">

2023-06-08 16:34 UTC, divinecharlotte commented on index.html
> +      <button class="resume-buttom">Get my resume</button>
- [ ] Kindly as requested by the previous reviewer consider adding button styling( Active, Hover, and Pressed) on your buttons to give a good user experience to the people visiting your website
 
<img width="634" alt="Screen Shot 2023-06-08 at 18 19 24" src="https://github.com/benjaMatteo96/my-portfolio/assets/60146030/d9f02bd3-98a7-43ae-94a8-d4c212a2ddd7">

2023-06-08 16:34 UTC, divinecharlotte commented on index.html
> +          <li class="tech-list">HTML</li>
- [ ] kindly consider giving your `li` some padding to make them meet their given design requirement in Figma check the images below to see the difference 
- your design 👇 
<img width="357" alt="Screen Shot 2023-06-08 at 18 25 18" src="https://github.com/benjaMatteo96/my-portfolio/assets/60146030/8b9e8dc3-5425-4a69-9a8c-0b99adb5de09">

- Figma design 👇  
<img width="416" alt="Screen Shot 2023-06-08 at 18 25 56" src="https://github.com/benjaMatteo96/my-portfolio/assets/60146030/977dbd86-6ba7-404e-9fc6-ed8792364ef0">

2023-06-08 16:34 UTC, divinecharlotte commented on index.html
> +      <img src="img/illustration 1- about me-mobile.svg" alt="" class="about-me-illustration-n1">
- [ ] Kindly consider adding this image as a background image because  its a decoration  and remember decorations are always backgrounded images, not `img` tags

2023-06-08 16:34 UTC, divinecharlotte commented on index.html
> +      <img src="./img/illustration 2-about me mobile.svg" alt="" class="about-me-illustration-n2">
- [ ] Kindly consider adding this image as a background image because  its a decoration  and remember decorations are always backgrounded images, not `img` tags

2023-06-08 18:04 UTC, benjaMatteo96 commented
@divinecharlotte Hey Divine, thanks for your time, hope you're fine. 
Updates:
- Add padding to li element from project section.
- Move the about images from HTML to CSS with a background-image behavior.

2023-06-09 00:10 UTC, jmonto55 requested changes

2023-06-09 00:10 UTC, jmonto55 commented on styles/style.css
> +  }
- [ ] Good work implementing the styles as requested by the previous reviewer. ✔️ However, please kindly ensure to fix the padding of your skills, as similar as possible to the Figma design. 🤓

Figma design. 👇🏽
![f](https://github.com/benjaMatteo96/my-portfolio/assets/116701485/3a8252c1-3ad1-4f41-be04-a130e7bcf058)

Your design. 👇🏽
![d](https://github.com/benjaMatteo96/my-portfolio/assets/116701485/9e787d85-04ca-4d65-bbb8-296c9000bfc4)

2023-06-09 00:10 UTC, jmonto55 commented on styles/style.css
> +    color: #36b37e;
- [ ] Good work styling your tech list elements here. ✔️ However, please kindly ensure to center the elements to follow the Figma design. 🤓

Figma design. 👇🏽
![f](https://github.com/benjaMatteo96/my-portfolio/assets/116701485/be8a9b38-5ee8-4eda-a6ec-f28aeebfadf2)

Your design. 👇🏽
![d](https://github.com/benjaMatteo96/my-portfolio/assets/116701485/214d0760-51b2-4726-b1bb-11d460c0100c)

2023-06-09 00:10 UTC, jmonto55 commented
# STATUS: REQUIRED CHANGES 🟡

Hi @benjaMatteo96 👋🏽, 

Great work on making the changes requested by a previous reviewer 👌
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

>![](https://camo.githubusercontent.com/d6579fddc8d090207bae8bed660e0dce450b33c4184427594c35e57690dbefa3/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f7a35634e716246624d544441342f67697068792e676966) 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 23:22 UTC, benjaMatteo96 commented
![webint-problem](https://github.com/benjaMatteo96/my-portfolio/assets/127891765/944f85c5-f8c6-47de-8c6a-0681c70b26d3)
![itsok](https://github.com/benjaMatteo96/my-portfolio/assets/127891765/36910d9e-411d-48bd-869a-42c49ff9f6a9)
Hello guys, I have the same issue that all the students, everything is ok on my local repository, but the problem persists, so the community just told me that reviewers are passed this issue, hope it's true.

2023-06-09 23:25 UTC, AbdusSattar-70 reviewed
## INVALID CRR
Hi @benjaMatteo96 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

## You have submitted a project, that didn't pass all the linters, Please make sure to pass the linters before submitting the re-review


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-10 16:31 UTC, vickymarz approved these changes
Hi @benjaMatteo96, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- Requested change implemented✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 16:50 UTC, merged